INSERT IGNORE INTO `fortunecookies` (`Id`, `Cookie`, `Language`) VALUES
	(1, 'They don\'t make bugs like Bunny anymore.', 'en'),
	(2, 'A programming language is low level when its programs require attention to the irrelevant', 'en'),
	(3, 'I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.', 'en'),
	(4, 'I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.', 'en'),
	(5, 'Some things Man was never meant to know. For everything else, there\'s Google.', 'en'),
	(6, 'Failure is not an option -- it comes bundled with Windows.', 'en'),
	(7, 'Computer games don\'t affect kids; I mean if Pac-Man affected us as kids, we\'d all be running around in darkened rooms, munching magic pills and listening to repetitive electronic music.', 'en'),
	(8, 'Artificial Intelligence usually beats natural stupidity.', 'en'),
	(9, 'To err is human... to really foul up requires the root password.', 'en'),
	(10, 'Like car accidents, most hardware problems are due to driver error.', 'en'),
	(11, 'If at first you don\'t succeed; call it version 1.0', 'en'),
	(12, 'If Python is executable pseudocode, then perl is executable line noise.', 'en'),
	(13, 'Programmers are tools for converting caffeine into code.', 'en'),
	(14, 'I can\'t uninstall it, there seems to be some kind of \'Uninstall Shield\'.', 'en'),
	(15, 'See daddy ? All the keys are in alphabetical order now.', 'en'),
	(16, 'Hey! It compiles! Ship it!', 'en'),
	(17, 'SUPERCOMPUTER: what it sounded like before you bought it.', 'en'),
	(18, 'Windows Vista: It\'s like upgrading from Bill Clinton to George W. Bush.', 'en'),
	(19, 'The more I C, the less I see.', 'en'),
	(20, 'Life would be so much easier if we only had the source code.', 'en'),
	(21, 'My software never has bugs. It just develops random features.', 'en'),
	(22, 'The only problem with troubleshooting is that sometimes trouble shoots back.', 'en'),
	(23, 'Crap... Someone knocked over my recycle bin... There\'s icons all over my desktop...', 'en'),
	(24, 'Relax, its only ONES and ZEROS !', 'en'),
	(25, 'rm -rf /bin/laden', 'en'),
	(26, 'I don\'t care if you ARE getting a PhD in it ! Get away from that damn computer and go find a woman !', 'en'),
	(27, 'The great thing about Object Oriented code is that it can make small, simple problems look like large, complex ones.', 'en'),
	(28, 'If brute force doesn\'t solve your problems, then you aren\'t using enough.', 'en'),
	(29, 'Unix is user-friendly. It\'s just very selective about who its friends are.', 'en'),
	(30, 'Microsoft: \'You\'ve got questions. We\'ve got dancing paperclips.\'', 'en'),
	(31, 'I\'m not anti-social; I\'m just not user friendly', 'en'),
	(32, 'The world is coming to an end... SAVE YOUR BUFFERS !', 'en'),
	(33, 'If you don\'t want to be replaced by a computer, don\'t act like one.', 'en'),
	(34, 'Better to be a geek than an idiot.', 'en'),
	(35, 'After Perl everything else is just assembly language.', 'en'),
	(36, 'There are 10 types of people in the world: those who understand binary, and those who don\'t.', 'en'),
	(37, 'Difference between a virus and windows ? Viruses rarely fail.', 'en'),
	(38, 'Helpdesk: There is an icon on your computer labeled \'My Computer\'. Double click on it., User: What\'s your computer doing on mine?', 'en'),
	(39, 'I think Microsoft named .Net so it wouldn’t show up in a Unix directory listing.', 'en'),
	(40, 'If debugging is the process of removing bugs, then programming must be the process of putting them in.', 'en'),
	(41, 'Computer dating is fine, if you\'re a computer.', 'en'),
	(42, 'Any fool can use a computer. Many do.', 'en'),
	(43, 'Hardware: The parts of a computer system that can be kicked.', 'en'),
	(44, 'Those who can\'t write programs, write help files.', 'en'),
	(45, 'You know you\'re a geek when... You try to shoo a fly away from the monitor with your cursor. That just happened to me. It was scary.', 'en'),
	(46, 'Computer language design is just like a stroll in the park. Jurassic Park, that is.', 'en');
