insert into fortunes ( text) values ('People are naturally attracted to you.');
insert into fortunes ( text) values ('You learn from your mistakes... You will learn a lot today.');
insert into fortunes ( text) values ('If you have something good in your life, don"t let it go!');
insert into fortunes ( text) values ('What ever you"re goal is in life, embrace it visualize it, and for it will be yours.');
insert into fortunes ( text) values ('Your shoes will make you happy today.');
insert into fortunes ( text) values ('You cannot love life until you live the life you love.');
insert into fortunes ( text) values ('Be on the lookout for coming events; They cast their shadows beforehand.');
insert into fortunes ( text) values ('Land is always on the mind of a flying bird.');
insert into fortunes ( text) values ('The man or woman you desire feels the same about you.');
insert into fortunes ( text) values ('Meeting adversity well is the source of your strength.');
insert into fortunes ( text) values ('A dream you have will come true.');
insert into fortunes ( text) values ('Our deeds determine us, as much as we determine our deeds.');
insert into fortunes ( text) values ('Never give up. You"re not a failure if you don"t give up.');
insert into fortunes ( text) values ('You will become great if you believe in yourself.');
insert into fortunes ( text) values ('There is no greater pleasure than seeing your loved ones prosper.');
insert into fortunes ( text) values ('You will marry your lover.');
insert into fortunes ( text) values ('A very attractive person has a message for you.');
insert into fortunes ( text) values ('You already know the answer to the questions lingering inside your head.');
insert into fortunes ( text) values ('It is now, and in this world, that we must live.');
insert into fortunes ( text) values ('You must try, or hate yourself for not trying.');
insert into fortunes ( text) values ('You can make your own happiness.');
insert into fortunes ( text) values ('The greatest risk is not taking one.');
insert into fortunes ( text) values ('The love of your life is stepping into your planet this summer.');
insert into fortunes ( text) values ('Love can last a lifetime, if you want it to.');
insert into fortunes ( text) values ('Adversity is the parent of virtue.');
insert into fortunes ( text) values ('Serious trouble will bypass you.');
insert into fortunes ( text) values ('A short stranger will soon enter your life with blessings to share.');
insert into fortunes ( text) values ('Now is the time to try something new.');
insert into fortunes ( text) values ('Wealth awaits you very soon.');
insert into fortunes ( text) values ('If you feel you are right, stand firmly by your convictions.');
insert into fortunes ( text) values ('If winter comes, can spring be far behind?');
insert into fortunes ( text) values ('Keep your eye out for someone special.');
insert into fortunes ( text) values ('You are very talented in many ways.');
insert into fortunes ( text) values ('A stranger, is a friend you have not spoken to yet.');
insert into fortunes ( text) values ('A new voyage will fill your life with untold memories.');
insert into fortunes ( text) values ('You will travel to many exotic places in your lifetime.');
insert into fortunes ( text) values ('Your ability for accomplishment will follow with success.');
insert into fortunes ( text) values ('Nothing astonishes men so much as common sense and plain dealing.');
insert into fortunes ( text) values ('Its amazing how much good you can do if you dont care who gets the credit.');
insert into fortunes ( text) values ('Everyone agrees. You are the best.');
insert into fortunes ( text) values ('LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.');
insert into fortunes ( text) values ('Jealousy doesn"t open doors, it closes them!');
insert into fortunes ( text) values ('It"s better to be alone sometimes.');
insert into fortunes ( text) values ('When fear hurts you, conquer it and defeat it!');
insert into fortunes ( text) values ('Let the deeds speak.');
insert into fortunes ( text) values ('You will be called in to fulfill a position of high honor and responsibility.');
insert into fortunes ( text) values ('The man on the top of the mountain did not fall there.');
insert into fortunes ( text) values ('You will conquer obstacles to achieve success.');
insert into fortunes ( text) values ('Joys are often the shadows, cast by sorrows.');
insert into fortunes ( text) values ('Fortune favors the brave.');